package jetbrains.mps.webr.coffeeScript.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.cells.EditorCell;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.nodeEditor.CellActionType;
import jetbrains.mps.nodeEditor.EditorCellAction;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class CoffeeParameterDeclaration_DeleteType {
  public static void setCellActions(EditorCell editorCell, SNode node, EditorContext context) {
    editorCell.setAction(CellActionType.DELETE, new CoffeeParameterDeclaration_DeleteType.CoffeeParameterDeclaration_DeleteType_DELETE(node));
  }

  public static class CoffeeParameterDeclaration_DeleteType_DELETE extends EditorCellAction {
    /*package*/ SNode myNode;

    public CoffeeParameterDeclaration_DeleteType_DELETE(SNode node) {
      this.myNode = node;
    }

    public String getDescriptionText() {
      return "Delete type";
    }

    public void execute(EditorContext editorContext) {
      this.execute_internal(editorContext, this.myNode);
    }

    public void execute_internal(EditorContext editorContext, SNode node) {
      SNodeOperations.deleteNode(SLinkOperations.getTarget(node, "type", true));
    }
  }
}
