package jetbrains.mps.webr.coffeeScript.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.cells.EditorCell;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.nodeEditor.CellActionType;
import jetbrains.mps.nodeEditor.EditorCellAction;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class CoffeeClosure_DeleteReturnType {
  public static void setCellActions(EditorCell editorCell, SNode node, EditorContext context) {
    editorCell.setAction(CellActionType.DELETE, new CoffeeClosure_DeleteReturnType.CoffeeClosure_DeleteReturnType_DELETE(node));
  }

  public static class CoffeeClosure_DeleteReturnType_DELETE extends EditorCellAction {
    /*package*/ SNode myNode;

    public CoffeeClosure_DeleteReturnType_DELETE(SNode node) {
      this.myNode = node;
    }

    public String getDescriptionText() {
      return "Remove return type hint";
    }

    public void execute(EditorContext editorContext) {
      this.execute_internal(editorContext, this.myNode);
    }

    public void execute_internal(EditorContext editorContext, SNode node) {
      SNodeOperations.deleteNode(SLinkOperations.getTarget(node, "returnType", true));
    }
  }
}
