package coffescript.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class CsArgList_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public CsArgList_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "coffescript.structure.CsArgList";
  }
}
