package coffescript.behavior;

/*Generated by MPS */


public class CsArrayExpression_BehaviorDescriptor extends CsExpression_BehaviorDescriptor {
  public CsArrayExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "coffescript.structure.CsArrayExpression";
  }
}
