package coffescript.behavior;

/*Generated by MPS */


public abstract class CsBaseVariableReference_BehaviorDescriptor extends CsExpression_BehaviorDescriptor {
  public CsBaseVariableReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "coffescript.structure.CsBaseVariableReference";
  }
}
