package coffescript.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;

public class CsBinaryOperator_Behavior {
  public static void init(SNode thisNode) {
  }

  public static boolean call_hasMorePriorityThan_1214291396529(SNode thisNode, SNode csBinaryOperator) {
    return SNodeOperations.getIndexInParent(SNodeOperations.getParent(thisNode)) <= SNodeOperations.getIndexInParent(SNodeOperations.getParent(csBinaryOperator));
  }
}
