package coffescript.behavior;

/*Generated by MPS */


public class CsBinaryOperator_BehaviorDescriptor extends CsOperator_BehaviorDescriptor {
  public CsBinaryOperator_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "coffescript.structure.CsBinaryOperator";
  }
}
