package coffescript.behavior;

/*Generated by MPS */


public class CsBinaryOperation_BehaviorDescriptor extends CsExpression_BehaviorDescriptor {
  public CsBinaryOperation_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "coffescript.structure.CsBinaryOperation";
  }
}
