package coffescript.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class CsBlock_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements CsFunctionBlock_BehaviorDescriptor {
  public CsBlock_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "coffescript.structure.CsBlock";
  }
}
