package coffescript.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class CsExpression_Behavior {
  public static void init(SNode thisNode) {
  }

  public static SNode call_getPrioritizedNode_3639529227212464656(SNode thisNode, SNode csBinaryOperator) {
    SNode result = thisNode;
    while (true) {
      SNode parent = SNodeOperations.getParent(result);
      if (!(SNodeOperations.isInstanceOf(parent, "coffescript.structure.CsBinaryOperation"))) {
        break;
      }
      SNode parentBinaryOperator = SLinkOperations.getTarget(SNodeOperations.cast(parent, "coffescript.structure.CsBinaryOperation"), "csBinaryOperator", false);
      if (CsBinaryOperator_Behavior.call_hasMorePriorityThan_1214291396529(csBinaryOperator, parentBinaryOperator)) {
        break;
      }
      result = SNodeOperations.cast(parent, "coffescript.structure.CsBinaryOperation");
    }
    return result;
  }
}
