package coffescript.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public abstract class CsExpression_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor implements CsFunctionBlock_BehaviorDescriptor {
  public CsExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "coffescript.structure.CsExpression";
  }
}
