package coffescript.behavior;

/*Generated by MPS */


public class CsExpressionWrapper_BehaviorDescriptor extends CsExpression_BehaviorDescriptor implements CsFunctionBlock_BehaviorDescriptor {
  public CsExpressionWrapper_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "coffescript.structure.CsExpressionWrapper";
  }
}
