package coffescript.behavior;

/*Generated by MPS */


public class CsExpressionStatement_BehaviorDescriptor extends CsStatement_BehaviorDescriptor {
  public CsExpressionStatement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "coffescript.structure.CsExpressionStatement";
  }
}
