package coffescript.behavior;

/*Generated by MPS */


public class CsFunctionExpression_BehaviorDescriptor extends CsExpression_BehaviorDescriptor implements CsIFunction_BehaviorDescriptor {
  public CsFunctionExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "coffescript.structure.CsFunctionExpression";
  }
}
