package coffescript.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class CsIfExpression_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public CsIfExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "coffescript.structure.CsIfExpression";
  }
}
