package coffescript.behavior;

/*Generated by MPS */


public class CsInitVariableExpression_BehaviorDescriptor extends CsExpression_BehaviorDescriptor {
  public CsInitVariableExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "coffescript.structure.CsInitVariableExpression";
  }
}
