package coffescript.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class CsOperatorList_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public CsOperatorList_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "coffescript.structure.CsOperatorList";
  }
}
