package coffescript.behavior;

/*Generated by MPS */

import jetbrains.mps.webr.javascriptInternal.behavior.Operator_BehaviorDescriptor;

public abstract class CsOperator_BehaviorDescriptor extends Operator_BehaviorDescriptor {
  public CsOperator_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "coffescript.structure.CsOperator";
  }
}
