package coffescript.behavior;

/*Generated by MPS */


public class CsParameterDeclaration_BehaviorDescriptor extends CsBaseVariableDeclaration_BehaviorDescriptor {
  public CsParameterDeclaration_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "coffescript.structure.CsParameterDeclaration";
  }
}
