package coffescript.behavior;

/*Generated by MPS */


public class CsParenthesesExpression_BehaviorDescriptor extends CsExpression_BehaviorDescriptor {
  public CsParenthesesExpression_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "coffescript.structure.CsParenthesesExpression";
  }
}
