package coffescript.behavior;

/*Generated by MPS */

import webr.javascript.behavior.FormalParameterList_BehaviorDescriptor;

public class CsParameterList_BehaviorDescriptor extends FormalParameterList_BehaviorDescriptor {
  public CsParameterList_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "coffescript.structure.CsParameterList";
  }
}
