package coffescript.behavior;

/*Generated by MPS */


public class CsParameterReference_BehaviorDescriptor extends CsBaseVariableReference_BehaviorDescriptor {
  public CsParameterReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "coffescript.structure.CsParameterReference";
  }
}
