package coffescript.behavior;

/*Generated by MPS */

import jetbrains.mps.lang.core.behavior.BaseConcept_BehaviorDescriptor;

public class CsPriorityGroup_BehaviorDescriptor extends BaseConcept_BehaviorDescriptor {
  public CsPriorityGroup_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "coffescript.structure.CsPriorityGroup";
  }
}
