package coffescript.behavior;

/*Generated by MPS */


public class CsReturnStatement_BehaviorDescriptor extends CsStatement_BehaviorDescriptor {
  public CsReturnStatement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "coffescript.structure.CsReturnStatement";
  }
}
