package coffescript.behavior;

/*Generated by MPS */


public class CsSplatsParameterDeclaration_BehaviorDescriptor extends CsParameterDeclaration_BehaviorDescriptor {
  public CsSplatsParameterDeclaration_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "coffescript.structure.CsSplatsParameterDeclaration";
  }
}
