package coffescript.behavior;

/*Generated by MPS */

import webr.javascript.behavior.JsStatement_BehaviorDescriptor;

public abstract class CsStatement_BehaviorDescriptor extends JsStatement_BehaviorDescriptor {
  public CsStatement_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "coffescript.structure.CsStatement";
  }
}
