package coffescript.behavior;

/*Generated by MPS */


public class CsUnaryOperation_BehaviorDescriptor extends CsExpression_BehaviorDescriptor {
  public CsUnaryOperation_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "coffescript.structure.CsUnaryOperation";
  }
}
