package coffescript.behavior;

/*Generated by MPS */


public class CsUnaryOperator_BehaviorDescriptor extends CsOperator_BehaviorDescriptor {
  public CsUnaryOperator_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "coffescript.structure.CsUnaryOperator";
  }
}
