package coffescript.behavior;

/*Generated by MPS */


public class CsVariableReference_BehaviorDescriptor extends CsBaseVariableReference_BehaviorDescriptor {
  public CsVariableReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "coffescript.structure.CsVariableReference";
  }
}
