package coffescript.behavior;

/*Generated by MPS */

import webr.javascript.behavior.IVarDeclaration_BehaviorDescriptor;

public class CsVariableDeclaration_BehaviorDescriptor extends CsBaseVariableDeclaration_BehaviorDescriptor implements IVarDeclaration_BehaviorDescriptor {
  public CsVariableDeclaration_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "coffescript.structure.CsVariableDeclaration";
  }
}
