package coffescript.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.style.Style;
import jetbrains.mps.nodeEditor.cells.EditorCell;
import jetbrains.mps.baseLanguage.editor.BaseLanguageStyle_StyleSheet;
import webr.javascript.editor.JavaScriptStylesheet_StyleSheet;
import jetbrains.mps.nodeEditor.style.StyleAttributes;
import jetbrains.mps.nodeEditor.MPSFonts;

public class CoffeeScriptStyleSheet_StyleSheet {
  public static Style getCsKeyword(final EditorCell cell) {
    Style style = new Style(cell);
    style.putAll(BaseLanguageStyle_StyleSheet.getKeyWord(null));
    return style;
  }

  public static Style getCsOperatorKeyword(final EditorCell cell) {
    Style style = new Style(cell);
    style.putAll(JavaScriptStylesheet_StyleSheet.getOperatorKeyword(null));
    style.set(StyleAttributes.FONT_STYLE, MPSFonts.BOLD_ITALIC);
    return style;
  }
}
