package coffescript.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.DefaultNodeEditor;
import jetbrains.mps.nodeEditor.cells.EditorCell;
import jetbrains.mps.nodeEditor.EditorContext;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.nodeEditor.cells.EditorCell_Collection;
import jetbrains.mps.nodeEditor.AbstractCellProvider;
import jetbrains.mps.nodeEditor.cells.EditorCell_Constant;

public class CsSplatsParameterDeclaration_Editor extends DefaultNodeEditor {
  public EditorCell createEditorCell(EditorContext editorContext, SNode node) {
    return this.createCollection_mbxpdp_a(editorContext, node);
  }

  private EditorCell createCollection_mbxpdp_a(EditorContext editorContext, SNode node) {
    EditorCell_Collection editorCell = EditorCell_Collection.createIndent2(editorContext, node);
    editorCell.setCellId("Collection_mbxpdp_a");
    editorCell.addEditorCell(this.createComponent_mbxpdp_a0(editorContext, node));
    editorCell.addEditorCell(this.createConstant_mbxpdp_b0(editorContext, node));
    return editorCell;
  }

  private EditorCell createComponent_mbxpdp_a0(EditorContext editorContext, SNode node) {
    AbstractCellProvider provider = new CsBaseVariableDeclaration_NameCellComponent(node);
    EditorCell editorCell = provider.createEditorCell(editorContext);
    return editorCell;
  }

  private EditorCell createConstant_mbxpdp_b0(EditorContext editorContext, SNode node) {
    EditorCell_Constant editorCell = new EditorCell_Constant(editorContext, node, "...");
    editorCell.setCellId("Constant_mbxpdp_b0");
    editorCell.setDefaultText("");
    return editorCell;
  }
}
