package jetbrains.mps.webr.coffeeScript.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class CoffeeScript_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("992a1545-afa2-4ddd-a91e-959803d71db3(jetbrains.mps.webr.coffeeScript)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
