package jetbrains.mps.webr.coffeeScript.structure;

/*Generated by MPS */

import webr.javascript.structure.JsBaseVariableDeclaration;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class CoffeeParameterDeclaration extends JsBaseVariableDeclaration {
  public static final String concept = "jetbrains.mps.webr.coffeeScript.structure.CoffeeParameterDeclaration";

  public CoffeeParameterDeclaration(SNode node) {
    super(node);
  }

  public static CoffeeParameterDeclaration newInstance(SModel sm, boolean init) {
    return (CoffeeParameterDeclaration) SModelUtil_new.instantiateConceptDeclaration("jetbrains.mps.webr.coffeeScript.structure.CoffeeParameterDeclaration", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static CoffeeParameterDeclaration newInstance(SModel sm) {
    return CoffeeParameterDeclaration.newInstance(sm, false);
  }
}
