package coffescript.test;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.util.plugin.run.MPSLaunch;
import jetbrains.mps.lang.test.runtime.BaseTransformationTest;
import org.junit.Test;
import jetbrains.mps.lang.test.runtime.BaseTestBody;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.behaviour.BehaviorManager;

@MPSLaunch
public class ParameterReferenceScope_Test extends BaseTransformationTest {
  @Test
  public void test_DataFlow989807379181106470() throws Throwable {
    this.initTest("C:/Users/Dmitry.Krasilschikov/MPSProjects/coffescript/coffescript.mpr", "r:0bd65ac5-b3f9-4ae3-92c4-8ca4284a8a87(coffescript.test)");
    this.runTest("coffescript.test.ParameterReferenceScope_Test$TestBody", "test_DataFlow989807379181106470", true);
  }

  @Test
  public void test_DataFlow989807379181106474() throws Throwable {
    this.initTest("C:/Users/Dmitry.Krasilschikov/MPSProjects/coffescript/coffescript.mpr", "r:0bd65ac5-b3f9-4ae3-92c4-8ca4284a8a87(coffescript.test)");
    this.runTest("coffescript.test.ParameterReferenceScope_Test$TestBody", "test_DataFlow989807379181106474", true);
  }

  @Test
  public void test_DataFlow3320097209922501865() throws Throwable {
    this.initTest("C:/Users/Dmitry.Krasilschikov/MPSProjects/coffescript/coffescript.mpr", "r:0bd65ac5-b3f9-4ae3-92c4-8ca4284a8a87(coffescript.test)");
    this.runTest("coffescript.test.ParameterReferenceScope_Test$TestBody", "test_DataFlow3320097209922501865", true);
  }

  @Test
  public void test_DataFlow1178807705579290663() throws Throwable {
    this.initTest("C:/Users/Dmitry.Krasilschikov/MPSProjects/coffescript/coffescript.mpr", "r:0bd65ac5-b3f9-4ae3-92c4-8ca4284a8a87(coffescript.test)");
    this.runTest("coffescript.test.ParameterReferenceScope_Test$TestBody", "test_DataFlow1178807705579290663", true);
  }

  @Test
  public void test_DataFlow1178807705579290696() throws Throwable {
    this.initTest("C:/Users/Dmitry.Krasilschikov/MPSProjects/coffescript/coffescript.mpr", "r:0bd65ac5-b3f9-4ae3-92c4-8ca4284a8a87(coffescript.test)");
    this.runTest("coffescript.test.ParameterReferenceScope_Test$TestBody", "test_DataFlow1178807705579290696", true);
  }

  @Test
  public void test_DataFlow1178807705579290729() throws Throwable {
    this.initTest("C:/Users/Dmitry.Krasilschikov/MPSProjects/coffescript/coffescript.mpr", "r:0bd65ac5-b3f9-4ae3-92c4-8ca4284a8a87(coffescript.test)");
    this.runTest("coffescript.test.ParameterReferenceScope_Test$TestBody", "test_DataFlow1178807705579290729", true);
  }

  @Test
  public void test_DataFlow5982157167539827576() throws Throwable {
    this.initTest("C:/Users/Dmitry.Krasilschikov/MPSProjects/coffescript/coffescript.mpr", "r:0bd65ac5-b3f9-4ae3-92c4-8ca4284a8a87(coffescript.test)");
    this.runTest("coffescript.test.ParameterReferenceScope_Test$TestBody", "test_DataFlow5982157167539827576", true);
  }

  @MPSLaunch
  public static class TestBody extends BaseTestBody {
    public void test_DataFlow989807379181106470() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("989807379181106470"), "jetbrains.mps.lang.test.structure.NodeOperation");
      BehaviorManager.getInstance().invoke(Object.class, SNodeOperations.cast(operation, "jetbrains.mps.lang.test.structure.NodeOperation"), "virtual_perform_1215601182156", new Class[]{SNode.class, SNode.class}, this.getRealNodeById("989807379181102156"));
    }

    public void test_DataFlow989807379181106474() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("989807379181106474"), "jetbrains.mps.lang.test.structure.NodeOperation");
      BehaviorManager.getInstance().invoke(Object.class, SNodeOperations.cast(operation, "jetbrains.mps.lang.test.structure.NodeOperation"), "virtual_perform_1215601182156", new Class[]{SNode.class, SNode.class}, this.getRealNodeById("989807379181104771"));
    }

    public void test_DataFlow3320097209922501865() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("3320097209922501865"), "jetbrains.mps.lang.test.structure.NodeOperation");
      BehaviorManager.getInstance().invoke(Object.class, SNodeOperations.cast(operation, "jetbrains.mps.lang.test.structure.NodeOperation"), "virtual_perform_1215601182156", new Class[]{SNode.class, SNode.class}, this.getRealNodeById("3320097209922501849"));
    }

    public void test_DataFlow1178807705579290663() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("1178807705579290663"), "jetbrains.mps.lang.test.structure.NodeOperation");
      BehaviorManager.getInstance().invoke(Object.class, SNodeOperations.cast(operation, "jetbrains.mps.lang.test.structure.NodeOperation"), "virtual_perform_1215601182156", new Class[]{SNode.class, SNode.class}, this.getRealNodeById("1178807705579290644"));
    }

    public void test_DataFlow1178807705579290696() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("1178807705579290696"), "jetbrains.mps.lang.test.structure.NodeOperation");
      BehaviorManager.getInstance().invoke(Object.class, SNodeOperations.cast(operation, "jetbrains.mps.lang.test.structure.NodeOperation"), "virtual_perform_1215601182156", new Class[]{SNode.class, SNode.class}, this.getRealNodeById("1178807705579290679"));
    }

    public void test_DataFlow1178807705579290729() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("1178807705579290729"), "jetbrains.mps.lang.test.structure.NodeOperation");
      BehaviorManager.getInstance().invoke(Object.class, SNodeOperations.cast(operation, "jetbrains.mps.lang.test.structure.NodeOperation"), "virtual_perform_1215601182156", new Class[]{SNode.class, SNode.class}, this.getRealNodeById("1178807705579290709"));
    }

    public void test_DataFlow5982157167539827576() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("5982157167539827576"), "jetbrains.mps.lang.test.structure.NodeOperation");
      BehaviorManager.getInstance().invoke(Object.class, SNodeOperations.cast(operation, "jetbrains.mps.lang.test.structure.NodeOperation"), "virtual_perform_1215601182156", new Class[]{SNode.class, SNode.class}, this.getRealNodeById("5982157167539827563"));
    }
  }
}
