package coffescript.test;

/*Generated by MPS */

import jetbrains.mps.baseLanguage.util.plugin.run.MPSLaunch;
import jetbrains.mps.lang.test.runtime.BaseTransformationTest;
import org.junit.Test;
import jetbrains.mps.lang.test.runtime.BaseTestBody;
import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SNodeOperations;
import jetbrains.mps.smodel.behaviour.BehaviorManager;

@MPSLaunch
public class VariableReferenceSearch_Test extends BaseTransformationTest {
  @Test
  public void test_DataFlow989807379181106493() throws Throwable {
    this.initTest("C:/Users/Dmitry.Krasilschikov/MPSProjects/coffescript/coffescript.mpr", "r:0bd65ac5-b3f9-4ae3-92c4-8ca4284a8a87(coffescript.test)");
    this.runTest("coffescript.test.VariableReferenceSearch_Test$TestBody", "test_DataFlow989807379181106493", true);
  }

  @Test
  public void test_DataFlow989807379181106492() throws Throwable {
    this.initTest("C:/Users/Dmitry.Krasilschikov/MPSProjects/coffescript/coffescript.mpr", "r:0bd65ac5-b3f9-4ae3-92c4-8ca4284a8a87(coffescript.test)");
    this.runTest("coffescript.test.VariableReferenceSearch_Test$TestBody", "test_DataFlow989807379181106492", true);
  }

  @Test
  public void test_DataFlow377098314686495581() throws Throwable {
    this.initTest("C:/Users/Dmitry.Krasilschikov/MPSProjects/coffescript/coffescript.mpr", "r:0bd65ac5-b3f9-4ae3-92c4-8ca4284a8a87(coffescript.test)");
    this.runTest("coffescript.test.VariableReferenceSearch_Test$TestBody", "test_DataFlow377098314686495581", true);
  }

  @Test
  public void test_DataFlow989807379181106490() throws Throwable {
    this.initTest("C:/Users/Dmitry.Krasilschikov/MPSProjects/coffescript/coffescript.mpr", "r:0bd65ac5-b3f9-4ae3-92c4-8ca4284a8a87(coffescript.test)");
    this.runTest("coffescript.test.VariableReferenceSearch_Test$TestBody", "test_DataFlow989807379181106490", true);
  }

  @Test
  public void test_DataFlow989807379181106489() throws Throwable {
    this.initTest("C:/Users/Dmitry.Krasilschikov/MPSProjects/coffescript/coffescript.mpr", "r:0bd65ac5-b3f9-4ae3-92c4-8ca4284a8a87(coffescript.test)");
    this.runTest("coffescript.test.VariableReferenceSearch_Test$TestBody", "test_DataFlow989807379181106489", true);
  }

  @Test
  public void test_DataFlow989807379181106488() throws Throwable {
    this.initTest("C:/Users/Dmitry.Krasilschikov/MPSProjects/coffescript/coffescript.mpr", "r:0bd65ac5-b3f9-4ae3-92c4-8ca4284a8a87(coffescript.test)");
    this.runTest("coffescript.test.VariableReferenceSearch_Test$TestBody", "test_DataFlow989807379181106488", true);
  }

  @Test
  public void test_DataFlow5982157167539858837() throws Throwable {
    this.initTest("C:/Users/Dmitry.Krasilschikov/MPSProjects/coffescript/coffescript.mpr", "r:0bd65ac5-b3f9-4ae3-92c4-8ca4284a8a87(coffescript.test)");
    this.runTest("coffescript.test.VariableReferenceSearch_Test$TestBody", "test_DataFlow5982157167539858837", true);
  }

  @Test
  public void test_DataFlow5982157167539858858() throws Throwable {
    this.initTest("C:/Users/Dmitry.Krasilschikov/MPSProjects/coffescript/coffescript.mpr", "r:0bd65ac5-b3f9-4ae3-92c4-8ca4284a8a87(coffescript.test)");
    this.runTest("coffescript.test.VariableReferenceSearch_Test$TestBody", "test_DataFlow5982157167539858858", true);
  }

  @Test
  public void test_DataFlow5982157167539858889() throws Throwable {
    this.initTest("C:/Users/Dmitry.Krasilschikov/MPSProjects/coffescript/coffescript.mpr", "r:0bd65ac5-b3f9-4ae3-92c4-8ca4284a8a87(coffescript.test)");
    this.runTest("coffescript.test.VariableReferenceSearch_Test$TestBody", "test_DataFlow5982157167539858889", true);
  }

  @MPSLaunch
  public static class TestBody extends BaseTestBody {
    public void test_DataFlow989807379181106493() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("989807379181106493"), "jetbrains.mps.lang.test.structure.NodeOperation");
      BehaviorManager.getInstance().invoke(Object.class, SNodeOperations.cast(operation, "jetbrains.mps.lang.test.structure.NodeOperation"), "virtual_perform_1215601182156", new Class[]{SNode.class, SNode.class}, this.getRealNodeById("989807379181104903"));
    }

    public void test_DataFlow989807379181106492() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("989807379181106492"), "jetbrains.mps.lang.test.structure.NodeOperation");
      BehaviorManager.getInstance().invoke(Object.class, SNodeOperations.cast(operation, "jetbrains.mps.lang.test.structure.NodeOperation"), "virtual_perform_1215601182156", new Class[]{SNode.class, SNode.class}, this.getRealNodeById("989807379181104911"));
    }

    public void test_DataFlow377098314686495581() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("377098314686495581"), "jetbrains.mps.lang.test.structure.NodeOperation");
      BehaviorManager.getInstance().invoke(Object.class, SNodeOperations.cast(operation, "jetbrains.mps.lang.test.structure.NodeOperation"), "virtual_perform_1215601182156", new Class[]{SNode.class, SNode.class}, this.getRealNodeById("377098314686495560"));
    }

    public void test_DataFlow989807379181106490() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("989807379181106490"), "jetbrains.mps.lang.test.structure.NodeOperation");
      BehaviorManager.getInstance().invoke(Object.class, SNodeOperations.cast(operation, "jetbrains.mps.lang.test.structure.NodeOperation"), "virtual_perform_1215601182156", new Class[]{SNode.class, SNode.class}, this.getRealNodeById("989807379181104935"));
    }

    public void test_DataFlow989807379181106489() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("989807379181106489"), "jetbrains.mps.lang.test.structure.NodeOperation");
      BehaviorManager.getInstance().invoke(Object.class, SNodeOperations.cast(operation, "jetbrains.mps.lang.test.structure.NodeOperation"), "virtual_perform_1215601182156", new Class[]{SNode.class, SNode.class}, this.getRealNodeById("989807379181104953"));
    }

    public void test_DataFlow989807379181106488() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("989807379181106488"), "jetbrains.mps.lang.test.structure.NodeOperation");
      BehaviorManager.getInstance().invoke(Object.class, SNodeOperations.cast(operation, "jetbrains.mps.lang.test.structure.NodeOperation"), "virtual_perform_1215601182156", new Class[]{SNode.class, SNode.class}, this.getRealNodeById("989807379181104971"));
    }

    public void test_DataFlow5982157167539858837() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("5982157167539858837"), "jetbrains.mps.lang.test.structure.NodeOperation");
      BehaviorManager.getInstance().invoke(Object.class, SNodeOperations.cast(operation, "jetbrains.mps.lang.test.structure.NodeOperation"), "virtual_perform_1215601182156", new Class[]{SNode.class, SNode.class}, this.getRealNodeById("5982157167539858815"));
    }

    public void test_DataFlow5982157167539858858() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("5982157167539858858"), "jetbrains.mps.lang.test.structure.NodeOperation");
      BehaviorManager.getInstance().invoke(Object.class, SNodeOperations.cast(operation, "jetbrains.mps.lang.test.structure.NodeOperation"), "virtual_perform_1215601182156", new Class[]{SNode.class, SNode.class}, this.getRealNodeById("5982157167539858856"));
    }

    public void test_DataFlow5982157167539858889() throws Exception {
      SNode operation = SNodeOperations.cast(this.getRealNodeById("5982157167539858889"), "jetbrains.mps.lang.test.structure.NodeOperation");
      BehaviorManager.getInstance().invoke(Object.class, SNodeOperations.cast(operation, "jetbrains.mps.lang.test.structure.NodeOperation"), "virtual_perform_1215601182156", new Class[]{SNode.class, SNode.class}, this.getRealNodeById("5982157167539858887"));
    }
  }
}
