package coffescript.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntentionsDescriptor;
import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.SModelReference;

public class IntentionsDescriptor extends BaseIntentionsDescriptor {
  public IntentionsDescriptor() {
    super(new ModuleReference("coffescript", "d8560b29-786e-42e5-8e6c-66382599eaf6"), SModelReference.fromString("r:31c8c445-88c8-4b5d-8803-63703a7e0633(coffescript.intentions)"));
  }

  public void init() {
    add(new CsSurroundWithParentheses_Intention(), "377098314686671953");
    add(new FlipCsBinaryOperation_Intention(), "377098314686671042");
  }
}
