package coffescript.structure;

/*Generated by MPS */

import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.Language;
import jetbrains.mps.smodel.MPSModuleRepository;

public class Coffescript_Language {
  public static ModuleReference MODULE_REFERENCE = ModuleReference.fromString("d8560b29-786e-42e5-8e6c-66382599eaf6(coffescript)");

  public static Language get() {
    return (Language) MPSModuleRepository.getInstance().getModule(MODULE_REFERENCE);
  }
}
