package coffescript.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.lang.core.structure.INamedConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class CsBaseVariableDeclaration extends BaseConcept implements INamedConcept {
  public static final String concept = "coffescript.structure.CsBaseVariableDeclaration";
  public static final String CPR_Initializable = "initializable";
  public static final String VARIABLE_NAME = "variableName";
  public static final String NAME = "name";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public CsBaseVariableDeclaration(SNode node) {
    super(node);
  }

  public String getVariableName() {
    return this.getProperty(CsBaseVariableDeclaration.VARIABLE_NAME);
  }

  public void setVariableName(String value) {
    this.setProperty(CsBaseVariableDeclaration.VARIABLE_NAME, value);
  }

  public String getName() {
    return this.getProperty(CsBaseVariableDeclaration.NAME);
  }

  public void setName(String value) {
    this.setProperty(CsBaseVariableDeclaration.NAME, value);
  }

  public String getShortDescription() {
    return this.getProperty(CsBaseVariableDeclaration.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(CsBaseVariableDeclaration.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(CsBaseVariableDeclaration.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(CsBaseVariableDeclaration.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(CsBaseVariableDeclaration.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(CsBaseVariableDeclaration.VIRTUAL_PACKAGE, value);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(CsBaseVariableDeclaration.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, CsBaseVariableDeclaration.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, CsBaseVariableDeclaration.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(CsBaseVariableDeclaration.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, CsBaseVariableDeclaration.SMODEL_ATTRIBUTE, node);
  }

  public static CsBaseVariableDeclaration newInstance(SModel sm, boolean init) {
    return (CsBaseVariableDeclaration) SModelUtil_new.instantiateConceptDeclaration("coffescript.structure.CsBaseVariableDeclaration", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static CsBaseVariableDeclaration newInstance(SModel sm) {
    return CsBaseVariableDeclaration.newInstance(sm, false);
  }
}
