package coffescript.structure;

/*Generated by MPS */

import jetbrains.mps.lang.core.structure.BaseConcept;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class CsExpression extends BaseConcept implements CsFunctionBlock {
  public static final String concept = "coffescript.structure.CsExpression";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public CsExpression(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(CsExpression.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(CsExpression.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(CsExpression.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(CsExpression.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(CsExpression.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(CsExpression.VIRTUAL_PACKAGE, value);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(CsExpression.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, CsExpression.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, CsExpression.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(CsExpression.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, CsExpression.SMODEL_ATTRIBUTE, node);
  }

  public static CsExpression newInstance(SModel sm, boolean init) {
    return (CsExpression) SModelUtil_new.instantiateConceptDeclaration("coffescript.structure.CsExpression", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static CsExpression newInstance(SModel sm) {
    return CsExpression.newInstance(sm, false);
  }
}
