package coffescript.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class CsExpressionStatement extends CsStatement {
  public static final String concept = "coffescript.structure.CsExpressionStatement";
  public static final String CS_EXPRESSION = "csExpression";

  public CsExpressionStatement(SNode node) {
    super(node);
  }

  public CsExpression getCsExpression() {
    return (CsExpression) this.getChild(CsExpression.class, CsExpressionStatement.CS_EXPRESSION);
  }

  public void setCsExpression(CsExpression node) {
    super.setChild(CsExpressionStatement.CS_EXPRESSION, node);
  }

  public static CsExpressionStatement newInstance(SModel sm, boolean init) {
    return (CsExpressionStatement) SModelUtil_new.instantiateConceptDeclaration("coffescript.structure.CsExpressionStatement", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static CsExpressionStatement newInstance(SModel sm) {
    return CsExpressionStatement.newInstance(sm, false);
  }
}
