package coffescript.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.INodeAdapter;

public interface CsFunctionBlock extends INodeAdapter {
  public static final String concept = "coffescript.structure.CsFunctionBlock";
}
