package coffescript.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.INodeAdapter;

public interface CsIFunction extends INodeAdapter {
  public static final String concept = "coffescript.structure.CsIFunction";
  public static final String CS_PARAMETER_LIST = "csParameterList";

  public CsParameterList getCsParameterList();
  public void setCsParameterList(CsParameterList node);
}
