package coffescript.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class CsParameterReference extends CsBaseVariableReference {
  public static final String concept = "coffescript.structure.CsParameterReference";

  public CsParameterReference(SNode node) {
    super(node);
  }

  public CsParameterDeclaration getCsParamaterDeclaration() {
    return this.ensureAdapter(CsParameterDeclaration.class, "csBaseVariableDeclaration", this.getCsBaseVariableDeclaration());
  }

  public void setCsParamaterDeclaration(CsParameterDeclaration node) {
    this.setCsBaseVariableDeclaration(node);
  }

  public static CsParameterReference newInstance(SModel sm, boolean init) {
    return (CsParameterReference) SModelUtil_new.instantiateConceptDeclaration("coffescript.structure.CsParameterReference", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static CsParameterReference newInstance(SModel sm) {
    return CsParameterReference.newInstance(sm, false);
  }
}
