package coffescript.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class CsReturnStatement extends CsStatement {
  public static final String concept = "coffescript.structure.CsReturnStatement";
  public static final String CS_EXPRESSION = "csExpression";

  public CsReturnStatement(SNode node) {
    super(node);
  }

  public CsExpression getCsExpression() {
    return (CsExpression) this.getChild(CsExpression.class, CsReturnStatement.CS_EXPRESSION);
  }

  public void setCsExpression(CsExpression node) {
    super.setChild(CsReturnStatement.CS_EXPRESSION, node);
  }

  public static CsReturnStatement newInstance(SModel sm, boolean init) {
    return (CsReturnStatement) SModelUtil_new.instantiateConceptDeclaration("coffescript.structure.CsReturnStatement", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static CsReturnStatement newInstance(SModel sm) {
    return CsReturnStatement.newInstance(sm, false);
  }
}
