package coffescript.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class CsUnaryOperation extends CsExpression {
  public static final String concept = "coffescript.structure.CsUnaryOperation";
  public static final String CS_UNARY_OPERATOR = "csUnaryOperator";
  public static final String CS_EXPRESSION = "csExpression";

  public CsUnaryOperation(SNode node) {
    super(node);
  }

  public CsUnaryOperator getCsUnaryOperator() {
    return (CsUnaryOperator) this.getReferent(CsUnaryOperator.class, CsUnaryOperation.CS_UNARY_OPERATOR);
  }

  public void setCsUnaryOperator(CsUnaryOperator node) {
    super.setReferent(CsUnaryOperation.CS_UNARY_OPERATOR, node);
  }

  public CsExpression getCsExpression() {
    return (CsExpression) this.getChild(CsExpression.class, CsUnaryOperation.CS_EXPRESSION);
  }

  public void setCsExpression(CsExpression node) {
    super.setChild(CsUnaryOperation.CS_EXPRESSION, node);
  }

  public static CsUnaryOperation newInstance(SModel sm, boolean init) {
    return (CsUnaryOperation) SModelUtil_new.instantiateConceptDeclaration("coffescript.structure.CsUnaryOperation", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static CsUnaryOperation newInstance(SModel sm) {
    return CsUnaryOperation.newInstance(sm, false);
  }
}
