package coffescript.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.webr.javascriptInternal.structure.UnaryOperator;
import webr.javascript.structure.JsType;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class CsUnaryOperator extends CsOperator {
  public static final String concept = "coffescript.structure.CsUnaryOperator";
  public static final String JS_UNARY_OPERATOR = "jsUnaryOperator";
  public static final String OPERAND_TYPE = "operandType";

  public CsUnaryOperator(SNode node) {
    super(node);
  }

  public UnaryOperator getJsUnaryOperator() {
    return (UnaryOperator) this.getReferent(UnaryOperator.class, CsUnaryOperator.JS_UNARY_OPERATOR);
  }

  public void setJsUnaryOperator(UnaryOperator node) {
    super.setReferent(CsUnaryOperator.JS_UNARY_OPERATOR, node);
  }

  public JsType getOperandType() {
    return (JsType) this.getChild(JsType.class, CsUnaryOperator.OPERAND_TYPE);
  }

  public void setOperandType(JsType node) {
    super.setChild(CsUnaryOperator.OPERAND_TYPE, node);
  }

  public static CsUnaryOperator newInstance(SModel sm, boolean init) {
    return (CsUnaryOperator) SModelUtil_new.instantiateConceptDeclaration("coffescript.structure.CsUnaryOperator", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static CsUnaryOperator newInstance(SModel sm) {
    return CsUnaryOperator.newInstance(sm, false);
  }
}
