package coffescript.structure;

/*Generated by MPS */

import webr.javascript.structure.IVarDeclaration;
import jetbrains.mps.smodel.SNode;
import java.util.Iterator;
import jetbrains.mps.lang.core.structure.Attribute;
import java.util.List;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class CsVariableDeclaration extends CsBaseVariableDeclaration implements IVarDeclaration {
  public static final String concept = "coffescript.structure.CsVariableDeclaration";
  public static final String SHORT_DESCRIPTION = "shortDescription";
  public static final String ALIAS = "alias";
  public static final String VIRTUAL_PACKAGE = "virtualPackage";
  public static final String SMODEL_ATTRIBUTE = "smodelAttribute";

  public CsVariableDeclaration(SNode node) {
    super(node);
  }

  public String getShortDescription() {
    return this.getProperty(CsVariableDeclaration.SHORT_DESCRIPTION);
  }

  public void setShortDescription(String value) {
    this.setProperty(CsVariableDeclaration.SHORT_DESCRIPTION, value);
  }

  public String getAlias() {
    return this.getProperty(CsVariableDeclaration.ALIAS);
  }

  public void setAlias(String value) {
    this.setProperty(CsVariableDeclaration.ALIAS, value);
  }

  public String getVirtualPackage() {
    return this.getProperty(CsVariableDeclaration.VIRTUAL_PACKAGE);
  }

  public void setVirtualPackage(String value) {
    this.setProperty(CsVariableDeclaration.VIRTUAL_PACKAGE, value);
  }

  public int getSmodelAttributesCount() {
    return this.getChildCount(CsVariableDeclaration.SMODEL_ATTRIBUTE);
  }

  public Iterator<Attribute> smodelAttributes() {
    return this.children(Attribute.class, CsVariableDeclaration.SMODEL_ATTRIBUTE);
  }

  public List<Attribute> getSmodelAttributes() {
    return this.getChildren(Attribute.class, CsVariableDeclaration.SMODEL_ATTRIBUTE);
  }

  public void addSmodelAttribute(Attribute node) {
    this.addChild(CsVariableDeclaration.SMODEL_ATTRIBUTE, node);
  }

  public void insertSmodelAttribute(Attribute prev, Attribute node) {
    this.insertChild(prev, CsVariableDeclaration.SMODEL_ATTRIBUTE, node);
  }

  public static CsVariableDeclaration newInstance(SModel sm, boolean init) {
    return (CsVariableDeclaration) SModelUtil_new.instantiateConceptDeclaration("coffescript.structure.CsVariableDeclaration", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static CsVariableDeclaration newInstance(SModel sm) {
    return CsVariableDeclaration.newInstance(sm, false);
  }
}
