package coffescript.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.smodel.SModel;
import jetbrains.mps.smodel.SModelUtil_new;
import jetbrains.mps.project.GlobalScope;

public class CsVariableReference extends CsBaseVariableReference {
  public static final String concept = "coffescript.structure.CsVariableReference";

  public CsVariableReference(SNode node) {
    super(node);
  }

  public CsVariableDeclaration getCsVariableDeclaration() {
    return this.ensureAdapter(CsVariableDeclaration.class, "csBaseVariableDeclaration", this.getCsBaseVariableDeclaration());
  }

  public void setCsVariableDeclaration(CsVariableDeclaration node) {
    this.setCsBaseVariableDeclaration(node);
  }

  public static CsVariableReference newInstance(SModel sm, boolean init) {
    return (CsVariableReference) SModelUtil_new.instantiateConceptDeclaration("coffescript.structure.CsVariableReference", sm, GlobalScope.getInstance(), init).getAdapter();
  }

  public static CsVariableReference newInstance(SModel sm) {
    return CsVariableReference.newInstance(sm, false);
  }
}
