package jetbrains.mps.webr.coffeeScript.behavior;

/*Generated by MPS */

import webr.javascript.behavior.JsBaseVariableDeclaration_BehaviorDescriptor;

public class CoffeeParameterDeclaration_BehaviorDescriptor extends JsBaseVariableDeclaration_BehaviorDescriptor {
  public CoffeeParameterDeclaration_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.webr.coffeeScript.structure.CoffeeParameterDeclaration";
  }
}
