package jetbrains.mps.webr.coffeeScript.behavior;

/*Generated by MPS */

import webr.javascript.behavior.JsExpression_BehaviorDescriptor;
import webr.javascript.behavior.JsStatementListHolder_BehaviorDescriptor;

public class CoffeeClosure_BehaviorDescriptor extends JsExpression_BehaviorDescriptor implements JsStatementListHolder_BehaviorDescriptor {
  public CoffeeClosure_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.webr.coffeeScript.structure.CoffeeClosure";
  }
}
