package jetbrains.mps.webr.coffeeScript.behavior;

/*Generated by MPS */

import jetbrains.mps.smodel.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;

public class CoffeeClosure_Behavior {
  public static void init(SNode thisNode) {
  }

  public static boolean call_isMultiline_4367459641968105261(SNode thisNode) {
    return SPropertyOperations.getBoolean(thisNode, "explicitMultiline") || ListSequence.fromList(SLinkOperations.getTargets(SLinkOperations.getTarget(thisNode, "statementList", true), "statement", true)).count() > 1;
  }
}
