package jetbrains.mps.webr.coffeeScript.behavior;

/*Generated by MPS */

import webr.javascript.behavior.JsBaseVariableReference_BehaviorDescriptor;

public class CoffeeParameterReference_BehaviorDescriptor extends JsBaseVariableReference_BehaviorDescriptor {
  public CoffeeParameterReference_BehaviorDescriptor() {
  }

  @Override
  public String getConceptFqName() {
    return "jetbrains.mps.webr.coffeeScript.structure.CoffeeParameterReference";
  }
}
