package jetbrains.mps.webr.coffeeScript.intentions;

/*Generated by MPS */

import jetbrains.mps.intentions.BaseIntentionsDescriptor;
import jetbrains.mps.project.structure.modules.ModuleReference;
import jetbrains.mps.smodel.SModelReference;

public class IntentionsDescriptor extends BaseIntentionsDescriptor {
  public IntentionsDescriptor() {
    super(new ModuleReference("jetbrains.mps.webr.coffeeScript", "992a1545-afa2-4ddd-a91e-959803d71db3"), SModelReference.fromString("r:3068107e-36cc-4ed8-8922-9db82525dbf3(jetbrains.mps.webr.coffeeScript.intentions)"));
  }

  public void init() {
    add(new ToggleExplicitMultiline_Intention(), "4367459641968148733");
  }
}
